name = "FallFest"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "653249e76a7bb9bc8cbd698f840328ae2a4b4c29f7ec83334df53dfa5cd4dd96"

[versions]
fabric = "0.10.2+build.210"
minecraft = "1.16.3"
