name = "FallFest"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfb85395bbf00cd58546bfe1eee9067bbebc91ac69d4c213f62ece1772f15961"

[versions]
fabric = "0.10.2+build.210"
minecraft = "1.16.3"
