name = "FallFest"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1dce300f93481697df74f69fde52fea2be9fe0013347dfe56e55ddec2159b81"

[versions]
fabric = "0.10.2+build.210"
minecraft = "1.16.3"
