name = "FallFest"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb7088e1de8e24218114f74a8db75dba7c09d85870c5fc3fc02edf0ade2c818d"

[versions]
fabric = "0.10.2+build.210"
minecraft = "1.16.3"
