name = "FallFest"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d97d2c1df587c760bcecf7fa1493360ca29efd902ecbbe5480f7b4c961a5a6d0"

[versions]
fabric = "0.10.2+build.210"
minecraft = "1.16.3"
