name = "ModFest - FallFest"
author = "ModFest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9627c8b0098157f9bb3d8b048277f9270038c610e568d4694b0bee2a43e47880"

[versions]
fabric = "0.10.2+build.210"
minecraft = "1.16.3"
