name = "Ars Theurgia"
filename = "arstheurgia-1.0.1.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/comofastm/ArsTheurgia/releases/download/1.0.3/arstheurgia-1.0.3.jar"
hash-format = "sha256"
hash = "4a6e359c2e3c2e2b56d2124b53e9a4f9768a4a36562adfcd374c3f5397e4d986"