name = "Ars Theurgia"
filename = "arstheurgia-1.0.1.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/comofastm/ArsTheurgia/releases/download/1.0.2/arstheurgia-1.0.2.jar"
hash-format = "sha256"
hash = "81a077bdabf9edc7818ce55d9dec2768f80b228f723f4c85f5f44d079213d5e8"