name = "Ars Theurgia"
filename = "arstheurgia-1.0.4.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/comofastm/ArsTheurgia/releases/download/1.0.4/arstheurgia-1.0.4.jar"
hash-format = "sha256"
hash = "9e3eba05c2586ab4602db18daa79d5bbf9cda008d05b0c07b79ae6e26838ad1b"