name = "Basic Billboards"
filename = "basicbillboards-0.0.2-alpha.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/FoundationGames/BasicBillboards/releases/download/0.0.2-alpha/basicbillboards-0.0.2-alpha.jar"
hash-format = "sha256"
hash = "48681bf76b4b43e7bad919d97ecd631fd9d2dafb41907022c53320abad8b2319"