name = "Basic Billboards"
filename = "basicbillboards-0.0.1-alpha.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/FoundationGames/BasicBillboards/releases/download/0.0.1-alpha/basicbillboards-0.0.1-alpha.jar"
hash-format = "sha256"
hash = "1ccf33533fae8017a661360248b5eba5cbbec02b66495a3422353250dbb681b9"