name = "Collectater"
filename = "collectater-1.0.0.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://cdn.discordapp.com/attachments/767132602003750912/767487012516528158/collectater-1.0.0.jar"
hash-format = "sha256"
hash = "0cb72a7af40218aaee16fddc0c4764b16612594a61c6cabc0b29332857018eab"