name = "Collectater"
filename = "collectater-1.0.0-SNAPSHOT.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://cdn.discordapp.com/attachments/432750457664962602/769658530948055070/collectater-1.0.0-SNAPSHOT.jar"
hash-format = "sha256"
hash = "f917a3be5d49779b3e2e06671c040bef9d263413546ac7b064cb550b34b4ec38"