name = "Cuddly Lamp"
filename = "cuddly-lamp-1.0.0.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/TheEpicBlock/cuddly-lamp/releases/download/1.0.0/cuddly-lamp-1.0.0.jar"
hash-format = "sha256"
hash = "f9c9abd067bce742b6a2405675ddb1a8703b3d976cac37f8551f825c7ce1c4b2"