name = "The Ghost of Fallfest"
filename = "fallfest116-ghost-1.16.3-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3088/200/fallfest116-ghost-1.16.3-1.2.2.jar"
hash-format = "murmur2"
hash = "2169096323"

[update]
[update.curseforge]
file-id = 3088200
project-id = 411694
release-channel = "beta"
