name = "FallPano"
filename = "fallpano-1.0.1.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/Earthcomputer/FallPano/releases/download/v1.0/fallpano-1.0.jar"
hash-format = "sha256"
hash = "81808e6d501897acb07267ad531a42d709b81ebe4edf17a1a1cb543c78d135bb"