name = "Kingdoms and Curses"
filename = "kingdoms-and-curses.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://cdn.discordapp.com/attachments/767132602003750912/767233857354334228/kingdoms-and-curses.jar"
hash-format = "sha256"
hash = "a1d1bb0d2a8fc0605038145612e87cf8d823f97ec7b34c8b94933d81805d7e1c"