name = "Phonos"
filename = "phonos-0.0.1-alpha.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/FoundationGames/Phonos/releases/download/0.0.2-alpha/phonos-0.0.2-alpha.jar"
hash-format = "sha256"
hash = "bc5c4b0512a8bc28f421309a5627a839b48226b2729c02b4aca774607e563dd9"