name = "Phonos"
filename = "phonos-0.0.1-alpha.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/FoundationGames/Phonos/releases/download/0.0.1-alpha/phonos-0.0.1-alpha.jar"
hash-format = "sha256"
hash = "8b89eba0ed0272e90eacf27baa42a6d13f00aaa076c1a121aec44ffbd621a1ca"