name = "Source3"
filename = "Source3-1.0.0.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/ramidzkh/Source3/releases/download/1.0.0/Source3-1.0.0.jar"
hash-format = "sha256"
hash = "64e7d834fd0ac96ace9b35c51e7a86c43cb40e719d8096009547cc4c78890d73"