name = "Source3"
filename = "Source3-1.0.1.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://github.com/ramidzkh/Source3/releases/download/1.0.1/Source3-1.0.1.jar"
hash-format = "sha256"
hash = "c0c9bb223c49eb9899c4d4b67548b96cabf1a0fe5ac569f43552393f884db3dc"