name = "TinTinTinTinTinTinTinTinTinTinTinTinTinTinTinTinTinTinTinTin"
filename = "fabric-example-mod-1.0.0.jar"
side = "both"

[option]
optional = false
default = false

[download]
url = "https://www.dropbox.com/s/tz7q63lsuh5t4hm/fabric-example-mod-1.0.0.jar?dl=1"
hash-format = "sha256"
hash = "399450917AF701CDAA08D2B2FAF653DA7E44F34E9314E85572C716AD0B21A82A"